package errorx

import "testing"

func TestError(*testing.T) {
	New("自定义错误")
}
